check50:
  dependencies:
    - "jupyter>=1.0"
    - "pandas>=1.0"
    - "nbformat>=5"
    - "matplotlib>=3.2"
    - "scipy>=1.4"
    - "spacy>=2.2"
    - "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.0/en_core_web_sm-2.2.0.tar.gz"
    - "scikit-learn>=0.22"
    - "nbconvert>=6.0"
  files:
    - !exclude "*"
    - !require "module 3.ipynb"
